/*
 * module: fundermental
 * file: ASTStart.java
 * date: 3/15/19 4:49 PM
 * author: VectorJu
 */
/* Generated By:JJTree: Do not edit this line. ASTStart.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.xlab.service_java_infrastructure.crypto;

public
class ASTStart extends SimpleNode {
  public ASTStart(int id) {
    super(id);
  }

  public ASTStart(ParseTree p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=cb56fa29e32117bff4f741f3d141d848 (do not edit this line) */
