/*
 * module: fundermental
 * file: ParseTreeTreeConstants.java
 * date: 3/15/19 4:49 PM
 * author: VectorJu
 */

/* Generated By:JavaCC: Do not edit this line. ParseTreeTreeConstants.java Version 6.1_2 */
package com.xlab.service_java_infrastructure.crypto;

public interface ParseTreeTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTEXPRESSION = 2;
  public int JJTOF = 3;
  public int JJTATTRIBUTE = 4;
  public int JJTNUMERICALATTRIBUTE = 5;
  public int JJTAREAATTRIBUTE = 6;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "Expression",
    "Of",
    "Attribute",
    "NumericalAttribute",
    "AreaAttribute",
  };
}
/* JavaCC - OriginalChecksum=88979833b55e2334c352e9e2ff691f73 (do not edit this line) */
